default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: hello_app_development

test:
  <<: *default
  database: hello_app_test

production:
  <<: *default
  database: hello_app_production
  username: hello_app
  password: <%= ENV['MYBLOG_DATABASE_PASSWORD'] %>
